### PR TITLE
Changed Start Configuration

### PR DESCRIPTION
**Pull request by HoleInTheSeat**
Changed Start Configuration to more accurate represent when the server is ready for client connections.

old was "DungeonDB Start" but clients are not actually able to connect until the server says "Game server connected"

# Description

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [x] You verify that the start command applied does not use a shell script
  * [x] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by gOOvER** [comment]
Somehow I can't believe that it is only due to the "started" parsing. This actually only indicates in Ptero that the server has been marked as started (regardless of whether this is true or not).

**Comment by RStivanson** [comment]
The change appears to be making the server started state change more consistent with when the server has actually finished started and is accepting connections. `DungeonDB start` is output prior to the world being loaded and the server is not accepting player connections at that time.

**Comment by gOOvER** [comment]
> The change appears to be making the server started state change more consistent with when the server has actually finished started and is accepting connections. `DungeonDB start` is output prior to the world being loaded and the server is not accepting player connections at that time.

sry, but thats not true and have nothing to do, that the server do not accept connection. You can add what you want as started stat. Thats only Ptero intern and have nothing to do with the server itself.

**Comment by gOOvER** [comment]
btw; wrong repo :)

Add your changes to the new Pelican Repo:
https://github.com/pelican-eggs/steamcmd

**Comment by RStivanson** [comment]
> > The change appears to be making the server started state change more consistent with when the server has actually finished started and is accepting connections. `DungeonDB start` is output prior to the world being loaded and the server is not accepting player connections at that time.
> 
> sry, but thats not true and have nothing to do, that the server do not accept connection. You can add what you want as started stat. Thats only Ptero intern and have nothing to do with the server itself.

Agreed, we are talking about different things.

**Comment by HoleInTheSeat** [comment]
I will re-create this on the correct repo.

What I had notice was when the server states "DungeonDB Start", the server still needed to load the entire world file and while it technically allowed clients to connect, they will consistently fail as the server prioritizes loading the world over connecting a client.

So if you try to connect after "DungeonDB Start" appears, The console will not display any incoming connections, and the client will say "Connecting..." and fail to connect. once the world file is fully loaded, the failed connection messages and the "Game server connected" message appear at the same time. Only after seeing "Game server connected" are clients actually able to connect successfully.

**Pull request closed without merging**
